package io.spring.domain;

public enum PageType {
    SITE_INDEX,
    SITE_PRODUCT,
    SITE_SEARCH,
    SITE_CART,
    SITE_ORDER,
    SITE_ORDER_DETAIL,
    SITE_CHECKOUT,
    ADMIN_INDEX,
    ADMIN_PRODUCT,
    ADMIN_PRODUCT_FORM,
    ADMIN_ORDER,
    ADMIN_STATISTICAL
}
